### ISSUE TITLE
Visual Studio 2019 Support

### ISSUE THREAD

**Issue by jbparker** [jgalentine007/VSGitDiff#4]
Thanks for the extension!

I was just wondering if you had any plans to add Visual Studio 2019 support.

I think it's largely just a bump in the vsixmanifest, but not sure if you knew otherwise.

Definitely wouldn't mind getting that started if you didn't mind!

**Comment by jgalentine007** [comment]
@jbparker If you want to give it a shot that would be great - I don't have 2019 installed yet to test. It's probably as simple as updating the [InstallationTarget](https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/). Thanks!

**Comment by jbparker** [comment]
Sounds great! I'll try to take a look tonight & send you a PR soon.
